name: dente
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  provider: ^6.1.5+1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  bloc: ^9.0.1
  loading_animation_widget: ^1.3.0
  top_snackbar_flutter: ^3.3.0
  match: ^0.4.1
  validatorless: ^1.2.5
  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0
  window_manager: ^0.5.1
  image_picker: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  dropdown_button2: ^2.3.9
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  flutter_pdfview: ^1.4.3
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  pdfx: ^2.9.2
  font_awesome_flutter: ^10.12.0
  lucide_icons: ^0.257.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  match_generator: ^0.4.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  window_manager: true
  image_path: "assets/image/logo.png"

flutter:

  
  uses-material-design: true

  assets:
    - assets/image/
    - assets/logo/
    - .env
  
  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fontes/mplus/italic.ttf
        - asset: assets/fontes/mplus/regular.ttf
        - asset: assets/fontes/mplus/bold.ttf
        - asset: assets/fontes/mplus/boldItalic.ttf
